steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ojt252/images/todolist', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/ojt252/images/todolist']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'todolist'
  - '--image'
  - 'us-central1-docker.pkg.dev/ojt252/images/todolist'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
# Grant Cloud Run Invoker role to allUsers to make the service publicly accessible
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'add-iam-policy-binding'
    - 'todolist'
    - '--member=allUsers'
    - '--role=roles/run.invoker'
    - '--region=us-central1'
    - '--platform=managed'
images:
- 'us-central1-docker.pkg.dev/ojt252/images/todolist'
