steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/images/todolist', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/images/todolist']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'todolist'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/images/todolist'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'BUCKET_NAME=ojt252-bucket'
# Grant Cloud Run Invoker role to allUsers to make the service publicly accessible
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'services'
    - 'add-iam-policy-binding'
    - 'todolist'
    - '--member=allUsers'
    - '--role=roles/run.invoker'
    - '--region=us-central1'
    - '--platform=managed'
# Grant Storage Object Admin role to the service account
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'projects'
    - 'add-iam-policy-binding'
    - '$PROJECT_ID'
    - '--member=serviceAccount:todolist-sa@$PROJECT_ID.iam.gserviceaccount.com'
    - '--role=roles/storage.objectAdmin'
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/images/todolist'
